exports.seed = function (knex) {
  const booksData = require('../../constants/booksData');
  return knex('books')
    .del()
    .then(function () {
      return knex('books').insert([
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
        {
          authorId: 1,
          name: 'Name of the Wind',
          genre: 'Fantasy',
          picture: booksData.nameOfTheWind.picture,
          description: booksData.nameOfTheWind.description,
          plotSummary: booksData.nameOfTheWind.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Final Empire',
          genre: 'Fantasy',
          picture: booksData.theFinalEmpire.picture,
          description: booksData.theFinalEmpire.description,
          plotSummary: booksData.theFinalEmpire.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Long Earth',
          genre: 'Sci-Fi',
          picture: booksData.theLongEarth.picture,
          description: booksData.theLongEarth.description,
          plotSummary: booksData.theLongEarth.plotSummary,
        },
        {
          authorId: 2,
          name: 'The Hero of Ages',
          genre: 'Fantasy',
          picture: booksData.theHeroofAges.picture,
          description: booksData.theHeroofAges.description,
          plotSummary: booksData.theHeroofAges.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Colour of Magic',
          genre: 'Fantasy',
          picture: booksData.theColourofMagic.picture,
          description: booksData.theColourofMagic.description,
          plotSummary: booksData.theColourofMagic.plotSummary,
        },
        {
          authorId: 3,
          name: 'The Light Fantastic',
          genre: 'Fantasy',
          picture: booksData.theLightFantastic.picture,
          description: booksData.theLightFantastic.description,
          plotSummary: booksData.theLightFantastic.plotSummary,
        },
      ]);
    });
};
