module.exports = {
  nameOfTheWind: {
    picture: `https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1610826947l/186074.jpg`,
    description: `The Name of the Wind, also called The Kingkiller Chronicle: Day One, is a heroic fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Man's Fear. It was published on March 27, 2007, by DAW Books.`,
    plotSummary: `The Kingkiller Chronicle takes place in the fictional world of Temerant, a large continent of which the known part, called the Four Corners of Civilization, is divided into several distinct nations and cultures. Much of the world follows a religion similar, though not identical, to medieval Christianity. Coexisting alongside the mortal world is the realm of The Fae, a parallel universe inhabited by supernatural creatures which can move between the two realms only when the moon is full. Magic exists in Temerant, too, but obeys a well-defined set of rules and principles that can only be exploited by those who have trained in its professional and scientific use.

    As the novel begins, the reader hears an old storyteller speaking of a famous old wizard called Taborlin the Great, who was captured by evil beings called the Chandrian. Escaping them, Taborlin fell from a great height—but since he knew the "Name of the Wind", he called it and the Wind came and set him down safely. In later parts of the book, characters are often skeptical of such stories. Some kinds of magic are taught in the University as academic disciplines and have daily-life applications (those who can afford it are able to buy magical lamps, for example, much better than the candles used by poorer people). However, most of the population does not have reliable knowledge of the magical disciplines and many still doubt that magicians can truly call upon the Wind. The Chandrian—whose appearance is supposedly heralded by flames turning blue—are often dismissed as mythical bogeymen.
    
    In the rural town of Newarre, the Waystone Inn is managed by an innkeeper named Kote and his assistant Bast. It is revealed that Kote is actually the renowned Kvothe: an unequaled sword fighter, magician, and musician, rumored to have killed a king - earning the title Kingkiller - and caused the present war in which the civilized world is embroiled. Bast is Kvothe's assistant and student and a prince of the Fae. Kvothe has gone into hiding and assumed the identity of Kote in order to keep a low profile. Kvothe saves a traveling scribe known as Chronicler from spider-like creatures called scrael, whereupon Chronicler, recognizing Kvothe, asks to record his story. Upon consenting, Kvothe tells Chronicler that this will take three days (corresponding to the planned trilogy of novels).
    
    Kvothe begins his story during his childhood, when he lived amongst a troupe of highly reputed traveling performers known as Edema Ruh. His loving parents train him from a young age as an actor, singer, and lute player. He does extremely well in all of these as in every other field to which he turns his hand. The troupe acquires the scholar and arcanist Abenthy, who trains Kvothe in science and sympathy: a discipline that creates links from one physical object to allow manipulation of another. Kvothe also witnesses Abenthy calling the wind to fend off suspicious townspeople and vows to discover the titular "name of the wind", permitting this control.
    
    Kvothe's father, the famous bard Arliden, starts composing what was to be the greatest of his works—a ballad of the ancient tragic hero Lanre. For this composition, Arliden starts collecting all the various tales of the mythical Chandrian and tries to get at the kernel of truth behind them—without explaining how this is related to Lanre. This inquiry turns out to have fatal consequences. When the troupe makes camp, Kvothe's mother sends him to gather sage in the surrounding woods. Upon returning, he finds his parents and all members of his troupe dead, and the all-too-real Chandrian seated around the campfire, which has turned blue. They disliked Arliden's researches and came to silence him and everybody else with whom he might have shared his findings. The eleven-year-old Kvothe is on the point of being killed by the Chandrian named Cinder when their leader, Lord Haliax, pressures them to depart due to the approach of some mysterious enemies of theirs.
    
    The traumatized Kvothe, alive but alone, spends three years in the slums of the city of Tarbean as a beggar and pickpocket. He is nudged out of this life by hearing a storyteller recount a story of how the hero Lanre became a renegade after the death of his beloved wife, went over to the evil forces he had fought and destroyed the cities with whose protection he was charged—and then changed his name and became himself the fearsome Lord Haliax of the Chandrian. Before Kvothe can ask more, the storyteller is arrested by the dominant Church on charges of heresy.
    
    Kvothe then resolves to get into the University, whose vast Archives include all kinds of accumulated knowledge, including, presumably, also on the Chandrian. Having through great effort obtained some minimal funds for both clothing and traveling, he sets out. En route Kvothe becomes enamored with a talented young woman known as Denna, who is a musician like himself. Kvothe enters the University despite his lack of tuition funds and performs admirably as a student, but faces continuous poverty and rivalries with the wealthy student Ambrose Jakis and the arrogant Master Hemme, who sees that Kvothe receives lashing for misbehaviour. A trick by Ambrose causes Kvothe to be banished from the Archives, hampering his research on the Chandrian, though he does very well in other fields of study, advancing extremely fast in academic degrees and gaining some loyal friends. Kvothe buys a lute despite his poverty, and performs brilliantly at a famous musical tavern to earn money, where he also befriends Denna again.
    
    Hearing reports of blue fire and murder at a rural wedding, he suspects the Chandrian and visits the site. There, Kvothe and Denna meet a local farmer who reported the blue fire, and later, as they are searching for the Chandrian, they encounter a draccus, which nearly destroys the local town before it is slain by Kvothe. He does succeed in discovering the reason the Chandrian murdered all of the wedding's participants: the bride's father had dug in the earth and discovered an old pot on which were paintings of all seven Chandrian; they came to recover the pot and kill anyone who may have seen it.
    
    Back at the University, Ambrose taunts Kvothe and breaks his lute. In a fit of rage, Kvothe unintentionally calls the name of the wind, breaking Ambrose's arm in the process. As a result of the confrontation, Kvothe is sentenced to further lashing but avoids expulsion. Thanks to his clear magical aptitude, he is also promoted in rank as a student under Master Namer Elodin's tutelage.
    
    In the inn at the present day, a mercenary possessed by a supposed skin dancer attacks the patrons and kills one of them. When Kvothe seemingly fails to use magic to help, the skin dancer dies after the local blacksmith's apprentice, Aaron, strikes the possessed mercenary with a rod of iron. The first day ends when Kvothe finishes the first chapter of his story and the town settles down for the night after the commotion. At night, Bast breaks into Chronicler's room and reveals Chronicler's coming was part of his plan all along. He threatens Chronicler, demanding that he focus Kote on the more heroic aspects of his story in the hope that he will abandon his apathy and return to his former heroic self.
    
    In the epilogue, it is implied Bast's fears are well-founded, as the present-day Kvothe is described as just a man "waiting to die."`,
  },
  theFinalEmpire: {
    picture: `https://mediad.publicbroadcasting.net/p/kwit/files/styles/x_large/public/201903/final_empire.jpg`,
    description: `Mistborn: The Final Empire, also known simply as Mistborn or The Final Empire, is a fantasy novel written by American author Brandon Sanderson. It was published on July 17, 2006 by Tor Books and is the first novel in the Mistborn trilogy, followed by The Well of Ascension in 2007 and The Hero of Ages in 2008.`,
    plotSummary: `Three years prior to the start of the novel, a half-skaa thief named Kelsier discovered that he was Mistborn and escapes the Pits of Hathsin, a brutal prison camp of the Lord Ruler. He returned to Luthadel, the capital city of the Final Empire, where he rounded up his old thieving crew for a new job: to overthrow the Final Empire by stealing its treasury and collapsing its economy.

    At the beginning of the novel, Vin, a wary and abused street urchin, is recruited by Kelsier's crew after Kelsier is notified by his brother, Marsh, that she is a Mistborn. Vin is trained by Kelsier's crew to develop her Allomantic powers, which include burning pewter to strengthen the body, burning tin to enhance the senses, and burning steel to gain a limited form of telekinesis over metal. She is also given the duty of spying on the nobility by attending opulent balls in Luthadel (the capital and center of the final empire), where she poses as Valette Renoux, niece to Lord Renoux, a nobleman working with Kelsier's crew. During these balls, she meets and falls in love with Elend Venture, heir to House Venture, the most powerful of the Luthadel noble houses. Elend flouts the rules of nobility culture and secretly plans to build a better society with his noble friends when they ascend to their respective house titles.
    
    Kelsier hopes to conquer the city by destabilizing it with a house war between the nobility and then invading with a skaa army. Once in control, he hopes to overthrow the Final Empire by stealing the Lord Ruler's hoard of atium, a precious metal which is the cornerstone of the Final Empire's economy. The crew succeeds in starting a house war by assassinating several powerful nobles and recruiting about seven thousand soldiers to join their cause. However, about three quarters of the soldiers are slaughtered when they foolishly attack an unimportant Final Empire garrison with the hopes of divine protection from Kelsier, who has spread rumors of his "supernatural" powers. The remaining soldiers are smuggled into Luthadel by Kelsier, who intends to continue the plan. Unfortunately, Marsh is discovered and seemingly killed, and Lord Renoux and his estate are seized and he is brought to be executed by the Canton of Inquisition, the police arm of the Final Empire. This Canton is made up of Steel Inquisitors, seemingly indestructible Allomancers with steel spikes driven through their eyes. Though Kelsier's crew manage to free most of Renoux's group and kill an Inquisitor, Kelsier is killed by the Lord Ruler himself in a dramatic confrontation in Luthadel's city square. Though these events appear to leave Kelsier's plan in shambles, it is revealed that his real plan was to become a martyred symbol of hope for Luthadel's superstitious skaa population. The skaa population reacts to his death by rising up and overthrowing the city with the help of Kelsier's army.
    
    Before his death, Kelsier had attempted to unlock the potential of the "Eleventh Metal" that he had acquired, which was rumored to be the Lord Ruler's weakness. He was unable to do so before his death, and left it to Vin to finish the job. With the Eleventh Metal, Vin goes to the imperial palace to kill the Lord Ruler. She is captured by the Canton of Inquisition and left in a cell to be tortured, but Sazed, her faithful servant, comes to her rescue. Using a magical discipline called Feruchemy, he helps Vin escape and recover her possessions. Marsh is revealed to be alive, having actually been made into a Steel Inquisitor; he betrays his fellow Inquisitors and slays them. Vin fights the Lord Ruler, who is revealed to be both an incredibly powerful Allomancer and a Feruchemist, the combination of which grants him incredible healing powers and eternal youth. Vin is almost destroyed by the Lord Ruler, but with hints from the Eleventh Metal and the unexpected magical aid of the mists, she manages to separate the Lord Ruler from his Feruchemical bracelets that provide him with constant youth, causing him to age rapidly. Vin uses a spear to kill the Lord Ruler, who with his last words ominously warns her of a great doom. The Final Empire collapses, though Elend is able to avoid total societal collapse by uniting Luthadel under a new system of democratic government.`,
  },
  theLongEarth: {
    picture: `https://m.media-amazon.com/images/I/51P-Im8F3oL.jpg`,
    description: `The Long Earth is the first novel in a collaborative science fiction series by British authors Terry Pratchett and Stephen Baxter.`,
    plotSummary: `The "Long Earth" is a (possibly infinite) series of parallel worlds that are similar to Earth, which can be reached by using an inexpensive device called a "Stepper". The "close" worlds are almost identical to "our" Earth (referred to as "Datum Earth"), others differ in greater and greater details, but all share one similarity: on none are there, or have there ever been, Homo sapiens – although the same cannot be said of earlier hominid species, especially Homo habilis.

    The book deals primarily with the journey of Joshua Valienté (a natural "Stepper") and Lobsang, who claims to be a Tibetan motorcycle repairman reincarnated as an artificial intelligence. The two chart a course to learn as much as possible about the parallel worlds, travelling millions of steps away from the original Earth. They encounter evidence of other humanoid species (referred to as trolls and elves); of human settlers who learned their gifts early – including Sally Linsay, daughter of the inventor of the stepper, who joins them on their expedition; and of an extinct race of bipedal dinosaur descendants. They also encounter warning signs of a great danger, millions of worlds away from "our" Earth, causing catastrophe as it moves. The book also deals with the effects of the explosion of available space on the people of Datum Earth and the new colonies and political movements that are spreading in the wake of Step Day.
    
    A young girl, Helen Green, and her family (with the exception of her brother, Rod, who is unable to step) trek across the long earth to form a new community, Reboot, on Earth West 101,754.
    
    After stepping across "The Gap" – a universe around two million steps from the Datum where the Earth no longer exists – Joshua and Lobsang encounter the threat that has caused the slow migration of Trolls away from the gap. First Person Singular is a being that absorbs other sentient life forms, eventually taking over everything on earth before stepping to the next. It currently cannot pass The Gap. Lobsang elects to stay in First Person Singular's universe and commune with it, in the hopes of convincing it not to advance further, or at least to not absorb all other sentients.
    
    Joshua and Sally return to Datum Earth back the way they came. Upon reaching Earth West 101,754, they hear news that Datum Madison has been destroyed in a nuclear explosion, the result of a bomb planted by a terrorist group of humans incapable of stepping (called "phobics" in the book's terminology). The book ends with the two of them briefly seeing the explosion site, before retreating to Earth West 1 Madison, where a backed-up instantiation of Lobsang contacts Joshua by phone.`,
  },
  theHeroofAges: {
    picture: `https://images-na.ssl-images-amazon.com/images/I/81RPa1UMMwL.jpg`,
    description: `Mistborn: The Hero of Ages is an epic fantasy novel written by American author Brandon Sanderson. It was published on October 14, 2008 by Tor Books and is the third novel in the Mistborn trilogy. It is preceded by The Well of Ascension in 2007 and followed by The Alloy of Law in the Mistborn: Era 2 series, Wax and Wayne in 2011.`,
    plotSummary: `The Hero of Ages is the prophesied savior of the Terris people, foretold to find and give up the power at the Well of Ascension, in a selfless act to save the world from the Deepness. However, the Terris prophecies proved to have been altered, in a ruse allowing the powerful force named Ruin to escape imprisonment.

    Ruin wanted to destroy the world instantaneously but his power was too weak, as part of it had been taken and hidden by the opposing force, Preservation, long ago. Freedom from the Well of Ascension enabled Ruin to directly affect the world more, increasing ashfall from the ashmounts and summoning earthquakes to break the world apart; he could also influence people and control entire koloss armies. He used his thousand years of imprisonment to plot his escape and the subsequent destruction he would reap.
    
    The Lord Ruler, in preparation of such an event, created storage caches containing resources such as food and water in cave complexes beneath certain cities, each one providing directions to the next. As Vin and Elend struggle to consolidate the remaining outposts of humanity, they hunt the storage caches, seeking hints left by the Lord Ruler and the missing atium stash. As they journey from cache to cache, the world itself begins to crumble, ash spewing forth in greater quantities, while the mists claim more people. The last two major unconquered cities are Fadrex City, which has reverted to the Lord Ruler's old structure of mass oppression under the obligator Yomen, and Urteau, a rebel city where the Skaa are free, the nobility overpowered, and a former commoner titled the Citizen rules with increasing violence.
    
    Sazed tries to establish diplomatic relations with the people of Urteau, while continuing to struggle with trauma from the recent death of his beloved, the Terriswoman Keeper Tindwyl. He studies religions, but has lost his own faith and yearns to find a religion that makes sense to him. He and Breeze work with Spook (who has developed strange abilities) to try and help Elend secretly take over Urteau. Meanwhile, TenSoon the kandra is imprisoned and sentenced to death by the kandra elders, while still trying to convince them that the kandra prophecies of the world ending are now happening, and that they must work together with the humans to save the world.
    
    Vin and Elend try to conquer the city of Fadrex and discover more about how their world works; they discover strange patterns in the numbers of people dying after being exposed to the mists, as well as secrets regarding the art of Hemalurgy, which is used to create the koloss, the kandra, and the Inquisitors. Fearing that Ruin will discover their plans, they are unable to discuss their plans with each other. Yomen, the King of Fadrex City, captures Vin on an infiltration mission gone wrong. Elend, left without any choice, takes another koloss army under his control, but the last remnants of Preservation appear to him, warning him to not attack the city. Shortly later, Preservation finally dies. On the verge of the attack, Vin escapes, and Ruin reveals his ability to seize ultimate control over the koloss. Ruin turns the koloss against Elend and Yomen's human armies, but before he can destroy them, Vin leads Ruin's attention and armies away to Luthadel. There, Marsh and the remaining Steel Inquisitors (who are under Ruin's control) battle Vin. On the verge of her death, Marsh briefly reasserts control and removes Vin's earring (which is actually a Hemalurgic spike), allowing Vin to draw upon the true power of the mists, Preservation's power. Vin ascends to become Preservation, trapped with Ruin upon another plane of existence, watching the world.
    
    The kandra finally accept their doom, and Sazed finds his faith in the ancient Terris religion and the Hero of the Ages. Urteau is saved, at a great physical cost to Spook, who has discovered that Ruin was influencing him with Hemalurgy. Elend leads the last of humanity to the Kandra homeland, the Pits of Hathsin, where Ruin's power, or body, has been stored. Ruin has been fooling Vin and Elend into leading him to his body, which turns out to be the atium stash, hidden in the Kandra homeland all along. Surrounded, and outnumbered, Elend, realizes that the Mists have been snapping mistings, and that he has been provided with an army of atium mistings. He leads a desperate battle against the koloss, in vain. Marsh appears again, and faces down Elend. Though Elend receives mystical aid from Vin, giving him unlimited metallic power, Marsh strikes Elend in the chest with an axe, which proves fatal. As he is dying, Elend reveals that his soldiers have burnt away all of Ruin's body, the atium, in battle, so now Ruin can never recover his missing power. Vin realizes that Preservation gave of himself to create mankind so that mankind would be able to manifest both Preservation's ability to create and Ruin's ability to destroy. Having both abilities within her, Vin attacks Ruin directly, killing herself/Preservation, but also destroying Ruin.
    
    Vin and many others thought that she was the Hero of Ages, but it is revealed to actually be the Terris Keeper Sazed. One major prophecy, "The Hero will bear the future of the world on his arms", referred to Sazed's Feruchemical copperminds on his arms. He uses the knowledge in these copperminds, along with the combined power of Preservation and Ruin, claimed from the fallen bodies of Vin and Elend, to help reshape the world, re-aligning the sun and planets to stabilize the world, changing the red, volcanic ecology into a new paradise of blue skies, green foliage, gentle warming sun and rainbow flowers. Spook, Ham, Breeze, and the other survivors emerge to this newly reformed world, and begin their mission of rebuilding society.`,
  },
  theColourofMagic: {
    picture: `https://images-na.ssl-images-amazon.com/images/I/91aC4cYBeQL.jpg`,
    description: `The Colour of Magic is a 1983 fantasy comedy novel by Terry Pratchett, and is the first book of the Discworld series. The first printing of the British edition consisted of only 506 copies. Pratchett has described it as "an attempt to do for the classical fantasy universe what Blazing Saddles did for Westerns."`,
    plotSummary: `The story begins in Ankh-Morpork, the biggest city on the Discworld. The main character is an incompetent and cynical wizard named Rincewind, who is hired as a guide to naive Twoflower, an insurance clerk from the Agatean Empire who has come to visit Ankh-Morpork. Thanks to the commonality of gold in his homeland, Twoflower, though only a clerk, is rich compared to inhabitants of Ankh-Morpork. Initially attempting to flee with his advance payment for agreeing to be Twoflower's guide, Rincewind is captured by the Patrician of Ankh-Morpork, who forces him to protect Twoflower, lest the tourist's death provoke the Agatean Emperor into invading Ankh-Morpork. After Twoflower is kidnapped by a gang of thieves and taken to the Broken Drum tavern, Rincewind stages a rescue alongside the Luggage, an indestructible, enchanted and sentient chest belonging to Twoflower. Before this, Twoflower convinces the Broken Drum's landlord to take out a fire insurance policy; the landlord subsequently attempts to burn down the tavern to claim the money, but ends up causing a fire that destroys the whole of Ankh-Morpork. Rincewind and Twoflower escape in the chaos.

    Rincewind and Twoflower travel towards the city of Quirm, unaware that their adventures on this journey are actually the subject of a boardgame played by the Gods of the Discworld. The pair are separated when they are attacked by a mountain troll summoned by Offler the Crocodile God. The ignorant Twoflower ends up being led to the Temple of Bel-Shamharoth, a being said to be the opposite of both good and evil, while Rincewind ends up imprisoned in a dryad-inhabited tree in the woods, where he watches the events in Bel Shamharoth's temple through a magical portal. The pair are reunited when Rincewind escapes into the temple through the portal, and they encounter Hrun the Barbarian, a parody of heroes in the Swords and Sorcery genre. The trio are attacked and nearly killed by Bel-Shamharoth, but escape when Rincewind accidentally blinds the creature with Twoflower's magical picture box. Hrun agrees to travel with and protect Twoflower and Rincewind in exchange for heroic pictures of him from the picture box.
    
    The trio visit the Wyrmberg, an upside-down mountain which is home to dragon-riders who summon their dragons by imagining them, and are separated when the riders attack them. Rincewind escapes capture but is forced by Kring, Hrun's sentient magical sword, to attempt to rescue his friends. Twoflower is imprisoned within the Wyrmberg, and because of his fascination with dragons, is able to summon one greater than those of the Wyrmberg riders, who he names Ninereeds, allowing him to escape captivity and save Rincewind from being killed in a duel with one of the three heirs of the Wyrmburg. Twoflower, Rincewind and Ninereeds snatch Hrun, but as they attempt to escape into the skies, Twoflower passes out from the lack of oxygen, causing Ninereeds to disappear. Hrun is saved by Liessa, but Rincewind and Twoflower find themselves falling to their deaths. In desperation, Rincewind manages to use the Wyrmberg's power to temporarily summon a passenger jet from the real world, before he and Twoflower fall into the ocean.
    
    The two of them are taken to the edge of the Discworld by the ocean currents and nearly carried over, but they are caught by the Circumfence, a huge net built by the nation of Krull to catch sea life and flotsam washed in from the rest of the Discworld. They are rescued by Tethis the sea troll, a being composed of water who had fallen off the edge of his own world and onto the Discworld, where he was subsequently enslaved by the Krullians. Rincewind and Twoflower are then taken by the Krullians to their capital, where they learn that the Krullians intend to discover the sex of Great A'Tuin by launching a space capsule over the edge of the Disc, and plan to sacrifice Rincewind and Twoflower to get the god Fate to smile on the voyage, Fate insisting on their sacrifice after they caused him to lose the earlier game. Rincewind and Twoflower attempt to escape, but end up stealing the capsule, which is launched with Twoflower inside, the tourist wishing to see the other worlds of the universe. Rincewind is unable to get into the capsule in time, and falls off the Disc alongside it, the Luggage following them soon after.
    
    The story segues into the beginning of The Light Fantastic.`,
  },
  theLightFantastic: {
    picture: `https://mlvzdnfuf2oo.i.optimole.com/se54NOM._Oyg~2dae4/w:auto/h:auto/q:90/https://www.setantabooks.com/wp-content/uploads/2013/06/15/terry-pratchett-the-light-fantastic-scaled.jpg`,
    description: `The Light Fantastic is a comic fantasy novel by Terry Pratchett, the second of the Discworld series. It was published on 2 June 1986, the first printing being of 1,034 copies. The title, taken from a poem by John Milton, in which it refers to dancing lightly with extravagance.`,
    plotSummary: `The book begins shortly after the ending of The Colour of Magic, with wizard Rincewind, Twoflower and the Luggage falling from the Discworld. They are saved when the Octavo, the most powerful book of magic on the Discworld, readjusts reality to prevent the loss of one of its eight spells, which has resided in Rincewind's head since his expulsion from Unseen University: Rincewind, Twoflower and the Luggage end up in the Forest of Skund. Meanwhile, the wizards of Ankh-Morpork use the Rite of Ashk-Ente to summon Death to find an explanation for the Octavo's actions. Death warns them that the Discworld will soon be destroyed by a huge red star unless the eight spells of the Octavo are read.

    Several orders of wizards travel to the forest of Skund to try and capture Rincewind, who is currently staying with Twoflower and the Luggage in a gingerbread house in the forest. In the subsequent chaos, Rincewind and Twoflower escape on an old witch's broom, while the Archchancellor of Unseen University is killed when his attempt to obtain the spell accidentally summons the Luggage on top of him, crushing him to death. His apprentice, Ymper Trymon, uses the opportunity to advance his own power, intending to obtain the eight spells for his own good.
    
    Rincewind and Twoflower run into a group of druids who have assembled a "computer" formed from large standing stones, and learn of the approaching red star. As Twoflower attempts to stop the druids from sacrificing a young woman named Bethan, Cohen the Barbarian, an octogenarian parody of Conan, attacks the druids. Twoflower is poisoned in the battle, forcing Rincewind to travel to Death's Domain to rescue him. The pair narrowly avoid being killed by Ysabell, Death's adopted daughter, and as they escape Death's Domain, Rincewind learns from the Octavo itself that it had arranged for its eighth spell to escape into his head, to ensure the spells would not be used before the right time.
    
    Rincewind and Twoflower travel with Cohen and Bethan to a nearby town, where the toothless Cohen leaves to have some dentures made for him, having learned of them from Twoflower. While he is gone, Rincewind, Twoflower and Bethan are attacked by a mob of people who believe the star is coming to destroy the Discworld in response to the presence of magic. The trio escape into one of many shops that sell strange and sinister goods and inexplicably vanish the next time a customer tries to find them. The existence of these shops is explained as being a curse by a sorcerer upon the shopkeeper for not having something in stock. They are able to return to Ankh-Morpork via the shop.
    
    As the star comes nearer and the magic on the Discworld becomes weaker, Trymon tries to put the seven spells still in the Octavo into his mind, in an attempt to save the world and gain ultimate power. However, the spells prove too strong for him and his mind becomes a door into the "Dungeon Dimensions", home to all manner of eldritch creatures. Rincewind and Twoflower manage to kill the now-mutated Trymon, and Rincewind reads all eight of the Octavo's spells aloud. This causes eight moons of the red star to crack open and reveal eight tiny world-turtles that follow their parent A'Tuin on a course away from the star. The Octavo then falls and is eaten by the Luggage.
    
    Twoflower and Rincewind part company as Twoflower decides to return home, leaving the Luggage with Rincewind as a parting gift. Cohen and Bethan also leave to get married. Rincewind decides to re-enroll in the university, believing that with the spell out of his head, he will finally be able to learn magic.`,
  },
};
